services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Heslo123
      POSTGRES_DB: warehouse_flex
    volumes:
      - warehouse_flex_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d warehouse_flex"]
      interval: 2s
      timeout: 5s
      retries: 30

volumes:
  warehouse_flex_db_data:
